### ISSUE TITLE
Foresee SSD cannot wake up after sleep

### ISSUE THREAD

**Issue by WickhamWei** [FluffyCuteOwO/Redmibook14-EE-hackintosh#5]
I have two Redmibook 14 EE, one is Samsung SSD, and the other is Forestee s50af512gb SSD. Foresee SSD cannot wake up after sleep. Any suggestions?

**Comment by michitta** [comment]
Hello! What version of mac OS are you using?

**Comment by WickhamWei** [comment]
> Hello! What version of mac OS are you using?

**Comment by WickhamWei** [comment]
> Hello! What version of mac OS are you using?

macOS 12.4, This problem occasionally occurs in Samsung SSD.

**Comment by michitta** [comment]
Unfortunately, I don't know exactly what the problem might be. In general, I recommend installing mac OS big sur due to sleep problems and Bluetooth on Monterey. If you were using Mac OS Big sur, I would send you a test build, which I use myself on an ongoing basis, but the problem is that it is not intended for new versions (there are no kexes, I did not add them)

**Comment by WickhamWei** [comment]
Thank you！ I'll try it.
